apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup-task
spec:
  steps:
    - name: cleanup
      image: alpine
      script: |
        echo "Cleaning up workspace"

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose-test-task
spec:
  steps:
    - name: run-tests
      image: python:3.8
      script: |
        echo "Running nose tests"
